server:
  port: 8080
spring:
  application:
    name: seckillsystem
  redis:
    host: 172.31.44.125
    port: 6379
    password: redis5sxfc
    database: 360
  rabbitmq:
    host: 172.31.44.130
    virtual-host: /
    port: 5672
    username: admin
    password: admin
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 3
    listener:
      simple:
        concurrency: 50
        max-concurrency: 50
        prefetch: 1
        acknowledge-mode: auto
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.31.32.234:3306/sxfcds2107558?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: sxfcds2107558
      password: SX_fcds2107558
      url: jdbc:mysql://172.31.32.234:3306/sxfcds2107558
mybatis-plus:
  type-aliases-package: com.jayce.seckillsystem.dao
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true