server:
  port: 80
spring:
  application:
    name: seckillsystem
  redis:
    host: 1.116.208.200
    port: 6379
    password: 123456
  rabbitmq:
    host: 1.116.208.200
    virtual-host: /
    port: 5672
    username: admin
    password: admin
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 3
    listener:
      simple:
        concurrency: 50
        max-concurrency: 50
        prefetch: 1
        acknowledge-mode: auto

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://1.116.208.200:3306/seckill_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: test
      password: '@Song123456'
      url: jdbc:mysql://1.116.208.200:3306/seckill_system
mybatis-plus:
  type-aliases-package: com.jayce.seckillsystem.dao
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true